server:
  port: 8080

spring:
  application:
    name: kafkaTest
  datasource:
    url: jdbc:mysql://localhost:3308/kafka
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update